version: "3.6"

services:
  db:
    image: postgres:14.2
    ports:
      - 5432:5432
    volumes:
      - "/.postgres:/var/lib/postgresql/data"
    env_file:
      - .env
#  web:
#    build: .
#    ports:
#      - "8000:8000"
#    env_file:
#      - .env
#    depends_on:
#      - postgres
